spring:
  application:
    name: flink-forge


flink:
  job-name: flink-forge-v1
  default-parallelism: 1


kafka:
  bootstrap-servers: "kafka:9092"
  src-topic: flink_src_topic_1
  sink-topic: flink_sink_topic_1
  group-id: grp.flink-forge
