# ============================
# [App] Business logic config
# ============================
app.flink.checkpoint.dir=file:///path/to/dir
app.flink.checkpoint.interval=100000000
app.flink.checkpoint.timeout=100000000
app.flink.checkpoint.min.pause=100000000
app.flink.checkpoint.tolerable.failure=100

# ============================
# [Kafka] Common config
# ============================
kafka.bootstrap-servers=localhost:9093
kafka.src-topic=kafka_src_topic
kafka.sink-topic=kafka_sink_topic
kafka.group-id=grp.flink-forge


# ============================
# [Flink] Common config
# ============================
flink.default-parallelism=1
flink.max-concurrent-checkpoints=1




# ==================================
# [Flink-job-specific] config : simple_flink_pipeline
# ==================================
job.simple-pipeline.name=simple-flink-job
job.simple-pipeline.kafka.sink-topic=kafka_sink_topic_1
job.simple-pipeline.kafka.group-id=grp.simple-flink-job


# ==================================
# [Flink-job-specific] config : windowed_aggregation
# ==================================
job.windowed-aggregation.name=windowed-aggregation-job
job.windowed-aggregation.kafka.sink-topic.user-aggregation=kafka_sink_topic
job.windowed-aggregation.kafka.sink-topic.event-aggregation=kafka_sink_topic_2
job.windowed-aggregation.kafka.group-id=grp.windowed-aggregation